version: '2'

services:
  database:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=tax-crud@123
      - MYSQL_DATABASE=tax-crud
    ports:
      - "33061:3306"

  zf:
    depends_on:
      - 'database'
    build: .
    links:
      - database
    ports:
      - "8080:80"
    volumes:
      - .:/var/www

volumes:
  database: