<?php

$title = 'Add new Tax Table';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('tax', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('effective_date'));
echo $this->formRow($form->get('operator_id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();