<?php

$this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js');
$this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css');

$title = 'Add new Tax Table';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Tax Table Description');

$effetive_date = $form->get('effectiveDate');
$effetive_date->setAttribute('placeholder', 'Effective Date');

$operator_id = $form->get('operator');
$operator_id->setAttribute('class', 'form-control');
$operator_id->setAttribute('placeholder', 'Operator');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('tax', [
    'action' => 'edit',
    'id'     => $id,
]));

$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($effetive_date) ?>
    <?= $this->formElement($effetive_date) ?>
    <?= $this->formElementErrors()->render($effetive_date, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($operator_id) ?>
    <?= $this->formElement($operator_id) ?>
    <?= $this->formElementErrors()->render($operator_id, ['class' => 'help-block']) ?>
</div>

<legend>Please add a taxes to this tax table</legend>
<button class="btn btn-success" onclick="return add_tax()">Add a new Tax</button>
<?= $this->formCollection($form->get('taxes')); ?>

<?php
echo $this->formSubmit($form->get('submit'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

?>

<script type="text/javascript">
function add_tax() {
    var currentCount = $('form > fieldset > fieldset').length;
    var template = $('form > fieldset > span').data('template');
    template = template.replace(/__index__/g, currentCount);

    $('form > fieldset').append(template);

    return false;
}
$(document).ready(function() {
    $('#effetiveDate_datepicker').datepicker({
        format: "yyyy-mm-dd"
    });
});
</script>