<?php

$this->headScript()->appendFile('https://unpkg.com/vue');
$this->headScript()->appendFile('https://unpkg.com/axios/dist/axios.min.js');
$this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js');

?>

<h1>Tax Table List</h1>
<div id="content">
    <tax-table-list v-on:taxlist="onShowTaxList" v-bind:tax-tables="taxTables"></tax-table-list>
    <tax-list-modal v-bind:tax-list="taxList"></tax-list-modal>
</div>

<script type="text/javascript">
    Vue.filter('formatDate', function(value) {
        if (value) {
            return moment(String(value)).format('DD/MM/YYYY');
        }
    });

    Vue.component('tax-list-modal', {
        template: `<div class="modal fade" id="myModal" tabindex="-1" role="dialog">\
                        <div class="modal-dialog" role="document">\
                            <div class="modal-content">\
                            <div class="modal-header">\
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>\
                                <h4 class="modal-title">Tax List</h4>\
                            </div>\
                            <div class="modal-body">\
                                <table class="table table-bordered table-striped">\
                                    <thead>\
                                        <tr>\
                                            <td>Value</td>\
                                            <td>From Value</td>\
                                            <td>Until Value</td>\
                                        </tr>\
                                    </thead>\
                                    <tbody>\
                                        <tr v-for="tax in taxList">\
                                            <td>{{tax.value}}</td>\
                                            <td>{{tax.fromValue}}</td>\
                                            <td>{{tax.untilValue}}</td>\
                                        </tr>\
                                    </tbody>\
                                </table>
                            </div>\
                            </div>\
                        </div>\
                    </div>`,
        props: ['taxList']
    });

    Vue.component('tax-table-list', {
        template: `<table class="table table-bordered table-striped">\
                        <thead>\
                            <tr>\
                                <td>Id</td>\
                                <td>Description</td>\
                                <td>Effective Date</td>\
                                <td>Operator</td>\
                                <td>Actions</td>\
                            </tr>\
                        </thead>\
                        <tbody>\
                            <tr v-for="taxTable in taxTables">\
                                <td>{{taxTable.id}}</td>\
                                <td>{{taxTable.description}}</td>\
                                <td>{{taxTable.effectiveDate.date | formatDate}}</td>\
                                <td>{{taxTable.operator.name}}</td>\
                                <td>\
                                    <a href="#" v-on:click="showTaxes(taxTable.taxes)" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span></a>\
                                    <a v-bind:href="'/tax/edit/' + taxTable.id"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>\
                                    <a href="#" v-on:click="removeTaxTable(taxTable)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>\
                                </td>\
                            </tr>\
                        </tbody>\
                   </table>`,
        props: ['taxTables'],
        methods: {
            showTaxes: function (taxList) {
                this.$emit('taxlist', taxList);
            },
            removeTaxTable: function (tax) {
                if(confirm("Are you sure?")) {
                    axios.post('/tax/delete/'+tax.id)
                        .then(function (response) {
                            alert('Deletado com sucesso');
                            listTaxTables();
                        })
                        .catch(function (error) {
                            console.log(error);
                        });
                }
            }
        }
    });

    var vm = new Vue({
        el: '#content',
        data: {
            taxTables: [],
            taxList: []
        },
        methods: {
            onShowTaxList: function(data) {
                this.taxList = data;
            }
        }
    })

    function listTaxTables() {
        axios.get('/tax/getTaxes')
            .then(function (response) {
                vm.taxTables = response.data.data.taxTables;
            })
            .catch(function (error) {
                console.log(error);
            });
    }

    listTaxTables();
</script>